# Generated by Django 3.2.2 on 2021-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('interest_pmt', models.FloatField()),
            ],
        ),
    ]
